version: '3.8'

services:
  prod_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    container_name: go_lang_prod   # This line sets the container name
  air_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    container_name: go_lang_air

  debugger:
    build: 
        context: .
        dockerfile: Dockerfile.debug
    ports:
        - "3000:3000"
        - "4000:4000"
    environment:
      - PORT=3000
    container_name: go_lang_debugger

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: rothira
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
