services:
  app:
    build:
      context: .
      dockerfile: Dockerfile          # Build the single image (React build + Go server)
    container_name: go_lang_app
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mongo

  # Optional: keep the debugger service if you still want Delve-based debugging
  debugger:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: go_lang_debugger
    working_dir: /app
    command: ["dlv", "debug", "--headless", "--listen=:4000", "--api-version=2", "--accept-multiclient", "--continue", "--", "-port", "8081"]
    environment:
      - PORT=8081
    volumes:
      - .:/app
    ports:
      - "8081:8081"
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: rothira
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
